apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ .Values.password | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    dispatch-service: {{ .Release.Name }}
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      dispatch-service: {{ .Release.Name }}
  template:
    metadata:
      labels:
        dispatch-service: {{ .Release.Name }}
    spec:
      {{- if not .Values.openShift }}
      securityContext:
        fsGroup: 999
      {{- end }}
      containers:
        - name: postgresql
          image: {{ .Values.image | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            {{- if not .Values.openShift }}
            runAsUser: 999
            runAsGroup: 999
            {{- end }}
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: postgresql
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: [pg_isready, -h, '127.0.0.1', -U, {{ .Values.username | quote }}, -d, {{ .Values.database | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 2
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
