import { useEffect, useRef, useState } from "react";
import { MagnifyingGlass, PushPin, X } from "@phosphor-icons/react";
import { Overview } from "../api";
import { AppRoute, routePath, shouldHandleNavigation } from "../routes";
import { useDeploymentCatalog } from "./DeploymentCatalog";
import { useNavigationPreferences } from "./navigationPreferences";

export function NavigationShortcuts({overview,route,onNavigate}:{overview:Overview;route:AppRoute;onNavigate:(route:AppRoute)=>void}){
 const {items}=useDeploymentCatalog();const {preferences,update,togglePin}=useNavigationPreferences(overview.identity?.id??"");
 const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const dialog=useRef<HTMLDivElement>(null);const trigger=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null;const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false);if(e.key!=="Tab")return;const nodes=[...(dialog.current?.querySelectorAll<HTMLElement>('a[href],button,input')??[])];const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};window.addEventListener("keydown",key);return()=>{window.removeEventListener("keydown",key);(previous?.isConnected?previous:trigger.current)?.focus();};},[open]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setOpen(v=>!v);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[]);
 const appID=route.deploymentID?overview.deployments.find(d=>d.id===route.deploymentID)?.appId??items.find(i=>i.current?.id===route.deploymentID||i.latest?.id===route.deploymentID)?.appId:route.applicationID;
 useEffect(()=>{if(appID)update(p=>({...p,recent:[appID,...p.recent.filter(id=>id!==appID)].slice(0,8)}));},[appID,overview.identity?.id]);
 const visible=items.filter(i=>`${i.appName} ${i.resourceName??""} ${i.environment} ${i.targetName}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(preferences.pins.includes(b.appId))-Number(preferences.pins.includes(a.appId))+(preferences.pins.includes(a.appId)===preferences.pins.includes(b.appId)?(preferences.recent.indexOf(a.appId)<0?99:preferences.recent.indexOf(a.appId))-(preferences.recent.indexOf(b.appId)<0?99:preferences.recent.indexOf(b.appId)):0));
 return <><button ref={trigger} className="command-trigger" onClick={()=>setOpen(true)} title="Search applications and environments (Ctrl/⌘ K)"><MagnifyingGlass size={16}/><span>Jump to…</span><kbd>⌘ K</kbd></button>{open&&<div className="command-backdrop"><div className="command-dialog" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="command-title"><header><h2 id="command-title">Jump to an environment</h2><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close command menu"><X size={18}/></button></header><input autoFocus aria-label="Search applications and environments" placeholder="Application, environment, or target…" value={query} onChange={e=>setQuery(e.target.value)}/><p>Pinned and recent applications first · Saved on this browser</p><ul>{visible.slice(0,30).map(item=>{const run=item.current??item.latest;const next:AppRoute=run?{view:"deployments",deploymentID:run.id}:{view:"deployments",deploymentApplicationID:item.resourceId??item.appId,deploymentStage:item.environment};return <li key={item.appId}><a aria-label={`Open ${item.resourceName||item.appName} ${item.environment} on ${item.targetName}`} href={routePath(next)} onClick={e=>{if(!shouldHandleNavigation(e))return;e.preventDefault();setOpen(false);onNavigate(next);}}><strong>{item.resourceName||item.appName}</strong><span>{item.environment} · {item.targetName}{preferences.recent.includes(item.appId)?" · Recent":""}</span></a><button className="icon-button" aria-label={`${preferences.pins.includes(item.appId)?"Unpin":"Pin"} ${item.appName} ${item.environment}`} aria-pressed={preferences.pins.includes(item.appId)} onClick={()=>togglePin(item.appId)}><PushPin size={16} weight={preferences.pins.includes(item.appId)?"fill":"regular"}/></button></li>;})}</ul>{!visible.length&&<p>No accessible environments match.</p>}<footer><a href="/deployments" onClick={e=>{if(!shouldHandleNavigation(e))return;e.preventDefault();setOpen(false);onNavigate({view:"deployments"});}}>All deployments</a><a href="/applications" onClick={e=>{if(!shouldHandleNavigation(e))return;e.preventDefault();setOpen(false);onNavigate({view:"applications"});}}>All applications</a></footer></div></div>}</>;
}
