ALTER TABLE apps ADD COLUMN helm_chart TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN helm_version TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN helm_repository TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN helm_values TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN helm_namespace TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN helm_release TEXT NOT NULL DEFAULT '';
