import { FormEvent, useEffect, useState } from "react";
import { Overview, request } from "./api";
import { BootstrapPlan, BootstrapReview } from "./TargetBootstraps";
import { MachineSnapshots } from "./MachineSnapshots";
import { StatusLabel } from "./ResourceTable";
import { canManageProject } from "./permissions";
import { isUIFeatureEnabled } from "./featureFlags";

type Managed = { sourceSnapshotId?: string; bootstrapId?: string; id: string; projectId: string; providerId: string; name: string; resourceId?: string; allocationState: string; enrollmentState: string; runtimeState: string; revision: number };
type Operation = { id: string; state: string; action: string; message?: string; resourceId?: string };
type Catalog = { id: string; name: string; manifest: { configurationSchema: { properties?: Record<string, { type?: string; title?: string; writeOnly?: boolean; enum?: string[] }> } } };
type Option = { id: string; name: string };
type Input = { sourceSnapshotId?: string; bootstrap?: BootstrapPlan; projectId: string; providerId: string; name: string; region: string; size: string; image: string; network: string; sshKeySecretId: string; config: Record<string, unknown>; secretRefs: Record<string, string> };
type Review = { id: string; name: string; digest: string; expiresAt: string; input: Input };
const root = "/api/v1/infrastructure/servers";
const post = <T,>(path: string, input?: unknown) => request<T>(path, { method: "POST", body: JSON.stringify(input ?? {}) });
const empty: Input = { projectId: "", providerId: "", name: "", region: "", size: "", image: "", network: "", sshKeySecretId: "", config: {}, secretRefs: {} };
const key = () => crypto.randomUUID();

export function ManagedServers({ overview, section, enforcePermissions = false }: { overview: Overview; section?: "machines" | "snapshots"; enforcePermissions?: boolean }) {
  const allowed = (project: string, permission: "infrastructure.create" | "infrastructure.modify" | "infrastructure.delete" | "infrastructure.restore" | "infrastructure.snapshot") => !enforcePermissions || canManageProject(overview, project, permission);
  const snapshotsEnabled = isUIFeatureEnabled(overview, "machineSnapshots");
  const operationVisible = (operation: Operation, server: Managed) => snapshotsEnabled || !(operation.action.startsWith("snapshot.") || operation.action === "server.promote" || operation.action === "create" && server.sourceSnapshotId);
  const operationAllowed = (project: string, operation: Operation) => allowed(project, operation.action === "snapshot.create" ? "infrastructure.snapshot" : operation.action === "snapshot.delete" ? "infrastructure.delete" : "infrastructure.modify") && (operation.action !== "server.promote" || allowed(project, "infrastructure.restore"));
  const [assignedKeys, setAssignedKeys] = useState<string[]>([]);
  const createProjects = overview.projects.filter(project => allowed(project.id, "infrastructure.create"));
  const [page, setPage] = useState(0);
  const [items, setItems] = useState<Managed[]>([]);
  const [catalog, setCatalog] = useState<Catalog[]>([]);
  const [input, setInput] = useState<Input>(empty);
  const [options, setOptions] = useState<Record<string, Option[]>>({});
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [review, setReview] = useState<Review | null>(null);
  const [confirmation, setConfirmation] = useState("");
  const [requestKey, setRequestKey] = useState("");
  const [operations, setOperations] = useState<Record<string, Operation[]>>({});
  const [enrollment, setEnrollment] = useState<{ server: string; nodeId: string; token: string; expiresAt: string } | null>(null);
  const [deletion, setDeletion] = useState<{ server: Managed; digest: string; summary: string; requestKey: string } | null>(null);
  const [adoption, setAdoption] = useState<{ server: Managed; resourceId: string } | null>(null);
  useEffect(() => { if (adoption?.server.sourceSnapshotId && !snapshotsEnabled) setAdoption(null); }, [adoption, snapshotsEnabled]);
  const refresh = async () => { const value = await request<Managed[]>(root); setItems(Array.isArray(value) ? value : []); };
  useEffect(() => { let active = true; const update = () => request<Managed[]>(root).then(value => { if (active) setItems(Array.isArray(value) ? value : []); }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : "Could not load machines."); }); void update(); const timer = setInterval(() => void update(), 5000); return () => { active = false; clearInterval(timer); }; }, []);
  useEffect(() => { setCatalog([]); setOptions({}); if (!input.projectId) return; let active = true; request<Catalog[]>(`/api/v1/projects/${encodeURIComponent(input.projectId)}/infrastructure/providers`).then(value => { if (active) setCatalog(Array.isArray(value) ? value : []); }).catch(() => { if (active) setError("Could not load approved providers."); }); return () => { active = false; }; }, [input.projectId]);
  useEffect(() => {
    setAssignedKeys([]);
    if (!enforcePermissions || overview.identity?.systemRole === "owner" || !input.projectId) return;
    let active = true;
    request<{ kind: string; resourceId: string }[]>(`/api/v1/infrastructure/assignments/${encodeURIComponent(input.projectId)}`).then(value => { if (active) setAssignedKeys((value || []).filter(item => item.kind === "ssh_key").map(item => item.resourceId)); }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : "Could not load assigned SSH keys."); });
    return () => { active = false; };
  }, [input.projectId, enforcePermissions, overview.identity?.id, overview.identity?.systemRole]);
  const sshKeys = enforcePermissions && overview.identity?.systemRole !== "owner" ? assignedKeys.map(id => ({ id, name: overview.secrets.find(item => item.id === id)?.name || id })) : overview.secrets.filter(secret => secret.type === "ssh_private_key");
  async function act(fn: () => Promise<void>) { setBusy(true); setError(""); try { await fn(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Infrastructure request failed."); } finally { setBusy(false); } }
  async function loadOptions() {
    await act(async () => {
      const entries = await Promise.all(["regions", "sizes", "images", "networks"].map(async kind => [kind, await post<Option[]>(`/api/v1/projects/${encodeURIComponent(input.projectId)}/infrastructure/providers/${encodeURIComponent(input.providerId)}/options`, { kind: kind === "networks" && input.sourceSnapshotId ? "restore-networks" : kind, config: input.config, secretRefs: input.secretRefs })] as const));
      setOptions(Object.fromEntries(entries));
    });
  }
  async function render(event: FormEvent) { event.preventDefault(); await act(async () => { setReview(await post<Review>(`${root}/review`, input)); setConfirmation(""); setRequestKey(key()); }); }
  async function accept(event: FormEvent) { event.preventDefault(); if (!review) return; await act(async () => { await post(root, { reviewId: review.id, digest: review.digest, confirmName: confirmation, requestKey }); setReview(null); setOpen(false); setInput(empty); await refresh(); }); }
  const provider = catalog.find(item => item.id === input.providerId);
  return <section className="server-section managed-servers" aria-labelledby="managed-servers-title">
    <div className="section-title"><div><h2 id="managed-servers-title">{section === "snapshots" ? "Snapshot restore" : section === "machines" ? "Machines" : "On-demand servers"}</h2><p>{section === "snapshots" ? "Restore a snapshot into a new isolated machine." : "Create machines through a provider and enroll their runtime agents."}</p></div>{section !== "snapshots" && createProjects.length > 0 && <button className="quiet-button" onClick={() => { setOpen(true); setReview(null); setInput(empty); }}>Create server</button>}</div>
    {error && <p role="alert" className="form-error">{error}</p>}
    {open && !review && <form className="connection-form inline-create" aria-label="Create on-demand server" onSubmit={event => void render(event)}>
      <div className="connection-grid">
        <label>Project<select required disabled={Boolean(input.sourceSnapshotId)} value={input.projectId} onChange={event => { setInput({ ...empty, projectId: event.target.value }); setOptions({}); }}><option value="">Choose project</option>{createProjects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>
        <label>Infrastructure provider<select required disabled={Boolean(input.sourceSnapshotId)} value={input.providerId} onChange={event => { setInput({ ...input, providerId: event.target.value, config: {}, secretRefs: {}, region: "", size: "", image: "", network: "" }); setOptions({}); }}><option value="">Choose provider</option>{catalog.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
        <label>Machine name<input required maxLength={80} value={input.name} onChange={event => setInput({ ...input, name: event.target.value })} /></label>
        <label>SSH public key<select required value={input.sshKeySecretId} onChange={event => setInput({ ...input, sshKeySecretId: event.target.value })}><option value="">Choose stored SSH key</option>{sshKeys.map(secret => <option key={secret.id} value={secret.id}>{secret.name}</option>)}</select><small>Only its public key is sent to the provider.</small></label>
        {Object.entries(provider?.manifest.configurationSchema.properties || {}).map(([name, field]) => <label key={name}>{field.title || name}{field.writeOnly ? <select value={input.secretRefs[name] || ""} onChange={event => setInput({ ...input, secretRefs: { ...input.secretRefs, [name]: event.target.value } })}><option value="">Choose secret</option>{overview.secrets.filter(secret => !["environment_variable", "environment_json", "json", "ssh_private_key"].includes(secret.type)).map(secret => <option key={secret.id} value={secret.id}>{secret.name}</option>)}</select> : field.enum ? <select value={String(input.config[name] ?? "")} onChange={event => setInput({ ...input, config: { ...input.config, [name]: event.target.value } })}><option value="">Choose value</option>{field.enum.map(value => <option key={value}>{value}</option>)}</select> : field.type === "boolean" ? <input type="checkbox" checked={Boolean(input.config[name])} onChange={event => setInput({ ...input, config: { ...input.config, [name]: event.target.checked } })} /> : <input type={field.type === "integer" || field.type === "number" ? "number" : "text"} value={String(input.config[name] ?? "")} onChange={event => setInput({ ...input, config: { ...input.config, [name]: field.type === "integer" || field.type === "number" ? Number(event.target.value) : event.target.value } })} />}</label>)}
      </div>
      <button type="button" className="quiet-button" disabled={busy || !provider} onClick={() => void loadOptions()}>Load machine choices</button>
      <div className="connection-grid">{([['region', 'regions', 'Region'], ['size', 'sizes', 'Size'], ['image', 'images', 'Image'], ['network', 'networks', 'Network']] as const).map(([field, kind, label]) => <label key={field}>{label}<select required value={input[field]} onChange={event => setInput({ ...input, [field]: event.target.value })}><option value="">Choose {label.toLowerCase()}</option>{(options[kind] || []).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>)}</div>
      <label><input type="checkbox" disabled={Boolean(input.sourceSnapshotId)} checked={Boolean(input.bootstrap)} onChange={event => setInput({ ...input, bootstrap: event.target.checked ? { targetName: input.name, method: "cloud_init", platform: "linux-amd64", imageFamily: "ubuntu-24.04", installRuntime: true, replaceIdentity: false } : undefined })} />Install and enroll the target agent with cloud-init</label>
      {input.bootstrap && <div className="connection-grid"><label>Agent architecture<select value={input.bootstrap.platform} onChange={event => setInput({ ...input, bootstrap: { ...input.bootstrap!, platform: event.target.value } })}><option value="linux-amd64">Linux amd64</option><option value="linux-arm64">Linux arm64</option></select></label><label>Bootstrap prerequisites<select value={input.bootstrap.imageFamily} onChange={event => setInput({ ...input, bootstrap: { ...input.bootstrap!, imageFamily: event.target.value, installRuntime: event.target.value === "ubuntu-24.04" } })}><option value="ubuntu-24.04">Ubuntu 24.04: install Docker, Compose v2 and Git</option><option value="existing-systemd">Image already has systemd, Python 3, Docker, Compose v2 and Git</option></select></label><p>The selected image must support cloud-init. The review pins the agent SHA-256 before the machine is created.</p></div>}
      <div className="connection-actions"><button type="button" className="quiet-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button" disabled={busy || !allowed(input.projectId, "infrastructure.create") || !!input.sourceSnapshotId && !allowed(input.projectId, "infrastructure.restore")}>Review creation</button></div>
    </form>}
    {review && <form className="connection-form inline-create" aria-label="Confirm server creation" onSubmit={event => void accept(event)}><h3>{review.input.sourceSnapshotId ? "Restore isolated clone" : "Create"} {review.name}</h3><p>{review.input.region} · {review.input.size} · {review.input.image} · {review.input.network}</p><p>The reviewed configuration is saved until {new Date(review.expiresAt).toLocaleTimeString()}. The provider may charge for the machine. Enrollment is required before deployments can run.</p>{review.input.sourceSnapshotId && <p>The clone receives fresh identities and independent disks. Copied workloads stay disabled; the clone remains quarantined after boot verification and is not a deployment target.</p>}{review.input.bootstrap && <BootstrapReview plan={review.input.bootstrap} />}<details><summary>Reviewed configuration</summary><pre>{JSON.stringify(review.input, null, 2)}</pre></details><label>Type {review.name} to confirm<input value={confirmation} onChange={event => setConfirmation(event.target.value)} /></label><div className="connection-actions"><button type="button" className="quiet-button" onClick={() => setReview(null)}>Back</button><button className="primary-button" disabled={busy || confirmation !== review.name || !allowed(review.input.projectId, "infrastructure.create") || !!review.input.sourceSnapshotId && !allowed(review.input.projectId, "infrastructure.restore")}>Create reviewed server</button></div></form>}
    {section !== "snapshots" && !items.length && <p className="section-empty">No on-demand servers yet. Creating machines requires an assigned provider and a project resource policy.</p>}
    {(section === "snapshots" ? [] : section ? items.slice(page * 20, page * 20 + 20) : items).map(item => <article className="connection-row" key={item.id}><div className="connection-identity"><strong>{item.name}</strong>{item.sourceSnapshotId && <small>Isolated clone of {item.sourceSnapshotId}</small>}<small>{item.resourceId || "Provider resource pending"}</small></div><div className="connection-metadata"><span>Allocation <StatusLabel state={item.allocationState} /></span><span>Enrollment <StatusLabel state={item.enrollmentState} /></span><span>Runtime <StatusLabel state={item.runtimeState} /></span></div><div className="connection-row-actions"><button className="table-action" disabled={busy} onClick={() => void act(async () => { const value = await request<Operation[]>(`${root}/${item.id}/operations`); setOperations(previous => ({ ...previous, [item.id]: value })); })}>Operations</button>{item.allocationState === "allocated" && <>{allowed(item.projectId, "infrastructure.modify") && !item.bootstrapId && item.enrollmentState !== "enrolled" && <button className="table-action" disabled={busy} onClick={() => void act(async () => { const result = await post<{ nodeId: string; token: string; expiresAt: string }>(`${root}/${item.id}/enrollment`); setEnrollment({ ...result, server: item.name }); await refresh(); })}>Issue enrollment token</button>}<button className="table-action" disabled={busy || !allowed(item.projectId, "infrastructure.delete")} onClick={() => void act(async () => { const result = await post<{ server: Managed; digest: string; summary: string }>(`${root}/${item.id}/delete-review`); setDeletion({ ...result, requestKey: key() }); setConfirmation(""); })}>Review deletion</button></>}</div>{(operations[item.id] || []).map(op => <div key={op.id}><p>{op.action} · {op.state}{op.message ? ` · ${op.message}` : ""}</p>{operationVisible(op, item) && op.state === "paused" && <button disabled={busy || !operationAllowed(item.projectId, op)} onClick={() => void act(async () => { await post(`/api/v1/infrastructure/operations/${op.id}/retry`); await refresh(); })}>Retry saved operation</button>}{operationVisible(op, item) && ["create", "snapshot.create"].includes(op.action) && ["pending", "running", "paused"].includes(op.state) && <button disabled={busy || !operationAllowed(item.projectId, op)} onClick={() => void act(async () => { await post(`/api/v1/infrastructure/operations/${op.id}/cancel`); await refresh(); })}>Cancel creation</button>}{operationVisible(op, item) && op.state === "unknown" && op.action === "create" && <button disabled={busy || !allowed(item.projectId, "infrastructure.modify")} onClick={() => { setAdoption({ server: item, resourceId: op.resourceId || "" }); setConfirmation(""); }}>Inspect and adopt</button>}</div>)}</article>)}
    {section === "machines" && items.length > 20 && <div className="resources-pagination"><span>{page * 20 + 1} to {Math.min(page * 20 + 20, items.length)} of {items.length}</span><button className="quiet-button" disabled={page === 0} onClick={() => setPage(value => value - 1)}>Previous</button><button className="quiet-button" disabled={(page + 1) * 20 >= items.length} onClick={() => setPage(value => value + 1)}>Next</button></div>}
    {section !== "machines" && isUIFeatureEnabled(overview, "machineSnapshots") && <MachineSnapshots enforcePermissions={enforcePermissions} overview={overview} servers={items} onRestore={snapshot => { setInput({ ...empty, sourceSnapshotId: snapshot.id, projectId: snapshot.projectId, providerId: snapshot.providerId, name: `${snapshot.name} clone`.slice(0, 80), image: snapshot.evidence?.image || "", bootstrap: { targetName: `${snapshot.name} clone`.slice(0, 80), method: "cloud_init", platform: "linux-amd64", imageFamily: "ubuntu-24.04", installRuntime: true, replaceIdentity: false } }); setReview(null); setOpen(true); setOptions({}); }} />}
    {enrollment && <div className="connection-form" role="status"><h3>Enroll {enrollment.server}</h3><p>Node: {enrollment.nodeId}. This one-use token expires at {new Date(enrollment.expiresAt).toLocaleTimeString()}. Install the runtime agent on this machine and use this node ID and token. A new token revokes previous enrollment.</p><label>One-use enrollment token<input readOnly value={enrollment.token} /></label><button onClick={() => setEnrollment(null)}>Dismiss token</button></div>}
    {adoption && (!adoption.server.sourceSnapshotId || snapshotsEnabled) && <form className="connection-form" onSubmit={event => { event.preventDefault(); void act(async () => { await post(`${root}/${adoption.server.id}/adopt`, { resourceId: adoption.resourceId, revision: adoption.server.revision, confirmName: confirmation }); setAdoption(null); await refresh(); }); }}><h3>Inspect owned resource for {adoption.server.name}</h3><p>The provider resource must carry this server's original project and request ownership labels.</p><label>Provider resource ID<input required value={adoption.resourceId} onChange={event => setAdoption({ ...adoption, resourceId: event.target.value })} /></label><label>Type {adoption.server.name} to confirm<input value={confirmation} onChange={event => setConfirmation(event.target.value)} /></label><button type="button" onClick={() => setAdoption(null)}>Cancel</button><button disabled={busy || confirmation !== adoption.server.name}>Inspect and adopt</button></form>}
    {deletion && <form className="connection-form" onSubmit={event => { event.preventDefault(); void act(async () => { await post(`${root}/${deletion.server.id}/delete`, { digest: deletion.digest, confirmName: confirmation, requestKey: deletion.requestKey }); setDeletion(null); await refresh(); }); }}><h3>Delete {deletion.server.name}</h3><p>{deletion.summary}</p><label>Type {deletion.server.name} to confirm<input value={confirmation} onChange={event => setConfirmation(event.target.value)} /></label><button type="button" onClick={() => setDeletion(null)}>Cancel</button><button disabled={busy || confirmation !== deletion.server.name}>Delete reviewed server</button></form>}
  </section>;
}
