import { useEffect, useState } from "react";
import { AccessOverview, api, Overview, request } from "./api";
import { canManageProject } from "./permissions";
import { useDeploymentCatalog } from "./deployments/DeploymentCatalog";
import { PageHeader } from "./PageHeader";
import "./OperationsPage.css";

type Audit = {id:string;actorId:string;actorName:string;impersonatorId?:string;projectId?:string;appId?:string;action:string;resourceId?:string;outcome:string;createdAt:string};
type Backup={id:string;engine:string;state:string;bytes:number;createdAt:string;verifiedAt?:string;message:string};
type Policy={projectId:string;logDays:number;runDays:number;keepRuns:number};
type Retention={logs:number;runs:number;protectedRuns:number;applied:boolean};
type Mapping={id:string;providerId:string;externalGroup:string;teamId:string};
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
export function OperationsPage({overview}:{overview:Overview}){
 const owner=overview.identity?.systemRole==="owner";
 const [tab,setTab]=useState("activity");
 const tabs=["activity","retention","ownership",...(owner?["backups","identity mapping"]:[])];
 return <div className="page-layout operations-page"><PageHeader view="access" title="Operations"/><div className="tab-bar" role="tablist" aria-label="Operations">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{tab==="activity"?<Activity overview={overview}/>:tab==="retention"?<RetentionControls overview={overview}/>:tab==="backups"&&owner?<Backups/>:tab==="identity mapping"&&owner?<IdentityMappings/>:<Ownership overview={overview}/>}</div>
}
function Activity({overview}:{overview:Overview}){
 const {items:catalog}=useDeploymentCatalog();
 const [project,setProject]=useState(""),[actor,setActor]=useState(""),[action,setAction]=useState(""),[items,setItems]=useState<Audit[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function load(before=""){setLoading(true);setError("");try{const q=new URLSearchParams({projectId:project,actorId:actor,action,before});const rows=await request<Audit[]>(`/api/v1/audit?${q}`);setItems(old=>before?[...old,...rows]:rows)}catch(e){setError(message(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[project]);
 return <section className="operations-panel"><h2>Activity</h2><form className="operations-form-row" onSubmit={e=>{e.preventDefault();void load()}}><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">All visible projects</option>{overview.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Actor ID<input value={actor} onChange={e=>setActor(e.target.value)} placeholder="All actors"/></label><label>Action<input value={action} onChange={e=>setAction(e.target.value)} placeholder="Exact action, or leave blank"/></label><button className="quiet-button" disabled={loading}>Filter</button></form>{error&&<p role="alert">{error}</p>}<div className="operations-table-scroll"><table><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Resource</th><th>Outcome</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{new Date(i.createdAt).toLocaleString()}</td><td>{i.actorName||i.actorId}{i.impersonatorId&&<small>Impersonated by {i.impersonatorId}</small>}</td><td>{i.action}</td><td>{overview.apps.find(a=>a.id===i.appId)?.name||catalog.find(a=>a.appId===i.appId)?.appName||i.resourceId||"Controller"}</td><td>{i.outcome}</td></tr>)}</tbody></table></div>{!items.length&&!loading&&<p>No matching activity. New actions appear here after this release.</p>}{items.length>=100&&<button className="quiet-button" disabled={loading} onClick={()=>void load(items.at(-1)?.id)}>Load older activity</button>}</section>
}
function RetentionControls({overview}:{overview:Overview}){
 const projects=overview.projects.filter(p=>canManageProject(overview,p.id,"project.manage"));const [project,setProject]=useState(projects[0]?.id??""),[policy,setPolicy]=useState<Policy|null>(null),[preview,setPreview]=useState<Retention|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
 useEffect(()=>{let alive=true;setPolicy(null);setPreview(null);setConfirm(false);if(project)request<Policy>(`/api/v1/projects/${project}/retention`).then(v=>{if(alive)setPolicy(v)}).catch(e=>{if(alive)setError(message(e))});return()=>{alive=false}},[project]);
 async function run(apply:boolean){if(!policy)return;setBusy(true);setError("");try{await request(`/api/v1/projects/${project}/retention`,{method:"PUT",body:JSON.stringify(policy)});setPreview(await request<Retention>(`/api/v1/projects/${project}/retention/${apply?"apply":"preview"}`,{method:"POST",body:JSON.stringify(apply?{confirm:project}:{})}));setConfirm(false)}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <section className="operations-panel"><h2>History retention</h2><p>Cleanup runs only when you apply it. Active deployments, successful releases, runtime baselines, and workflow references remain protected.</p><label>Project<select value={project} onChange={e=>setProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{!projects.length&&<p>Project admin access is required to manage retention.</p>}{policy&&<><div className="operations-form-row">{([['logDays','Keep logs for days'],['runDays','Keep failed runs for days'],['keepRuns','Minimum runs per application']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min={key==="keepRuns"?5:1} value={policy[key]} onChange={e=>{setPolicy({...policy,[key]:Number(e.target.value)});setPreview(null);setConfirm(false)}}/></label>)}</div><button className="quiet-button" disabled={busy} onClick={()=>void run(false)}>{busy?"Working…":"Save and preview cleanup"}</button>{preview&&<div className="operations-notice"><p>{preview.applied?"Removed":"Eligible for removal"}: {preview.logs} log lines, {preview.runs} failed runs. {preview.protectedRuns} runs protected.</p>{!preview.applied&&(preview.logs>0||preview.runs>0)&&(confirm?<><p>Remove the eligible history from this project? This cannot be undone.</p><button className="danger-button" disabled={busy} onClick={()=>void run(true)}>Remove eligible history</button><button className="quiet-button" onClick={()=>setConfirm(false)}>Cancel</button></>:<button className="quiet-button" onClick={()=>setConfirm(true)}>Review removal</button>)}</div>}</>}{error&&<p role="alert" className="error">{error}</p>}</section>
}
function Backups(){
 const [data,setData]=useState<{configured:boolean;backups:Backup[]}|null>(null),[busy,setBusy]=useState(""),[error,setError]=useState("");async function load(){setData(await request("/api/v1/operations/backups"))}useEffect(()=>{void load().catch(e=>setError(message(e)))},[]);
 async function act(id?:string){setBusy(id||"new");setError("");try{await request(`/api/v1/operations/backups${id?`/${id}/verify`:""}`,{method:"POST",body:"{}"})}catch(e){setError(message(e))}finally{await load().catch(e=>setError(message(e)));setBusy("")}}
 return <section className="operations-panel"><div className="operations-inline-heading"><h2>Controller backups</h2><button className="primary-button" disabled={!!busy||!data?.configured} onClick={()=>void act()}>{busy==="new"?"Creating backup…":"Create backup"}</button></div><p>Includes the controller database and vault key. Keep an off-server copy in protected storage. Restore checks use a disposable database and never replace the running controller.</p>{data&&!data.configured&&<p>Configure the controller master key and backup directory to enable backups.</p>}{error&&<p className="error" role="alert">{error}</p>}<div className="operations-table-scroll"><table><thead><tr><th>Created</th><th>Database / size</th><th>Restore verification</th><th>Action</th></tr></thead><tbody>{data?.backups.map(b=><tr key={b.id}><td>{new Date(b.createdAt).toLocaleString()}<small>{b.id}</small></td><td>{b.engine} · {(b.bytes/1048576).toFixed(1)} MiB</td><td>{b.verifiedAt?`Verified ${new Date(b.verifiedAt).toLocaleString()}`:b.state}<small>{b.message}</small></td><td><button className="quiet-button" disabled={!!busy||b.state==="failed"||b.state==="creating"} onClick={()=>void act(b.id)}>{busy===b.id?"Checking restore…":"Verify restore"}</button></td></tr>)}</tbody></table></div>{!data?.backups.length&&<p>No controller backups recorded yet.</p>}<p className="muted-cell">PostgreSQL restore checks require compatible client tools and permission to create and drop a temporary database. External application data and volumes need their own backups.</p></section>
}
function Ownership({overview}:{overview:Overview}){
 const {items:catalog}=useDeploymentCatalog();
 const apps=[...new Map([...overview.apps.map(a=>({id:a.id,name:a.name,projectId:a.projectId})),...catalog.map(a=>({id:a.appId,name:a.appName,projectId:a.projectId}))].map(a=>[a.id,a])).values()].filter(a=>canManageProject(overview,a.projectId,"project.configure"));const [app,setApp]=useState(apps[0]?.id??""),[access,setAccess]=useState<AccessOverview|null>(null),[kind,setKind]=useState("user"),[principal,setPrincipal]=useState(""),[error,setError]=useState(""),[status,setStatus]=useState("");useEffect(()=>{const project=apps.find(a=>a.id===app)?.projectId;if(project)request<AccessOverview>(`/api/v1/projects/${project}/owner-candidates`).then(setAccess).catch(e=>setError(message(e)))},[app]);useEffect(()=>{let alive=true;setStatus("");if(app)request<{principalType:string;principalId:string}>(`/api/v1/apps/${app}/owner`).then(v=>{if(alive){setKind(v.principalType||"user");setPrincipal(v.principalId||"")}}).catch(e=>{if(alive)setError(message(e))});return()=>{alive=false}},[app]);
 useEffect(()=>{if(!apps.some(a=>a.id===app))setApp(apps[0]?.id??"")},[app,apps.map(a=>a.id).join(",")]);
 async function save(){setError("");try{await request(`/api/v1/apps/${app}/owner`,{method:"PUT",body:JSON.stringify({principalType:kind,principalId:principal})});setStatus("Application owner saved.")}catch(e){setError(message(e))}}
 return <section className="operations-panel"><h2>Application ownership</h2><p>Record the responsible person or team. Ownership labels do not grant access.</p><div className="operations-form-row"><label>Application<select value={app} onChange={e=>setApp(e.target.value)}>{apps.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Owner type<select value={kind} onChange={e=>{setKind(e.target.value);setPrincipal("")}}><option value="user">Person</option><option value="team">Team</option></select></label><label>Owner<select value={principal} onChange={e=>setPrincipal(e.target.value)}><option value="">Unassigned</option>{kind==="team"?access?.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>):access?.users.map(u=><option key={u.id} value={u.id}>{u.displayName||u.username}</option>)}</select></label><button className="primary-button" disabled={!app} onClick={()=>void save()}>Save owner</button></div>{error&&<p role="alert">{error}</p>}{status&&<p role="status">{status}</p>}</section>
}
function IdentityMappings(){
 const [access,setAccess]=useState<AccessOverview|null>(null),[rows,setRows]=useState<Mapping[]>([]),[provider,setProvider]=useState(""),[team,setTeam]=useState(""),[group,setGroup]=useState(""),[error,setError]=useState("");async function load(){const [a,m]=await Promise.all([api.access(),request<Mapping[]>("/api/v1/identity-team-mappings")]);setAccess(a);setRows(m)}useEffect(()=>{void load().catch(e=>setError(message(e)))},[]);
 async function save(){setError("");try{await request("/api/v1/identity-team-mappings",{method:"POST",body:JSON.stringify({providerId:provider,teamId:team,externalGroup:group})});setGroup("");await load()}catch(e){setError(message(e))}}async function remove(id:string){try{await request(`/api/v1/identity-team-mappings/${id}`,{method:"DELETE"});await load()}catch(e){setError(message(e))}}
 return <section className="operations-panel"><h2>Identity team mappings</h2><p>Map verified GitHub teams to Dispatch teams. Membership refreshes at sign-in and requires the provider's read:org scope. Manual team memberships remain separate.</p><form className="operations-form-row" onSubmit={e=>{e.preventDefault();void save()}}><label>Sign-in provider<select required value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Choose provider</option>{access?.providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>GitHub team<input required value={group} onChange={e=>setGroup(e.target.value)} placeholder="organization/team-slug"/></label><label>Dispatch team<select required value={team} onChange={e=>setTeam(e.target.value)}><option value="">Choose team</option>{access?.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button className="primary-button">Add mapping</button></form>{error&&<p className="error" role="alert">{error}</p>}<div className="operations-table-scroll"><table><thead><tr><th>Provider</th><th>External team</th><th>Dispatch team</th><th>Action</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{access?.providers.find(p=>p.id===m.providerId)?.name}</td><td>{m.externalGroup}</td><td>{access?.teams.find(t=>t.id===m.teamId)?.name}</td><td><button className="quiet-button" onClick={()=>void remove(m.id)}>Remove mapping</button></td></tr>)}</tbody></table></div></section>
}
