import { useEffect, useState } from "react";
import { ArrowsClockwise, CheckCircle, WarningCircle } from "@phosphor-icons/react";
import { Overview, request, ServiceConnection } from "./api";
import { ApplicationDeploymentLink } from "./deployments/DeploymentCatalog";
import { canManageProject } from "./permissions";
import "./ServiceOperations.css";

type Consumer = { appId: string; appName: string; alias: string; appliedRevision: number; redeploymentRequired: boolean; targetName: string; environment: string; deploymentId?: string; canRedeploy: boolean; reason?: string };
type Impact = { serviceId: string; revision: number; consumers: Consumer[] };
export function ServiceOperations({ service, overview, onChanged, onBindings }: { onBindings?: (appId: string) => void; service: ServiceConnection; overview: Overview; onChanged: () => Promise<void> }) {
 const [impact,setImpact]=useState<Impact|null>(null), [selected,setSelected]=useState<string[]>([]), [error,setError]=useState(""),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[result,setResult]=useState("");
 const consumerVersion=JSON.stringify(service.consumers.map(c=>[c.appId,c.alias,c.appliedRevision,c.redeploymentRequired]));
 const deploymentVersion=JSON.stringify([...new Set(service.consumers.map(c=>c.appId))].sort().map(appId=>{const latest=overview.deployments.filter(d=>d.appId===appId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id))[0];return [appId,latest?.id,latest?.state]}));
 const manage=canManageProject(overview,service.projectId,"project.configure")&&canManageProject(overview,service.projectId,"deployment.run");
 useEffect(()=>{let alive=true;setImpact(null);setSelected([]);setConfirm(false);setError("");request<Impact>(`/api/v1/services/${service.id}/impact`).then(v=>{if(alive)setImpact(v)}).catch(e=>{if(alive)setError(String(e.message))});return()=>{alive=false}},[service.id,service.revision,consumerVersion,deploymentVersion]);
 async function redeploy(){setBusy(true);setError("");try{const rows=await request<{appId:string;deployment?:{id:string};error?:string}[]>(`/api/v1/services/${service.id}/redeploy`,{method:"POST",body:JSON.stringify({revision:impact?.revision,appIds:selected,confirm:true})});setResult(`${rows.filter(r=>r.deployment).length} deployment(s) accepted.${rows.some(r=>r.error)?" Some applications were not accepted. Refresh before retrying.":""}`);setConfirm(false);setSelected([]);await onChanged()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="service-impact"><div className="operations-inline-heading"><h3>Application impact</h3><span>{impact?.consumers.filter(c=>c.redeploymentRequired).length??0} bindings need redeployment</span></div>
 {error&&<p role="alert" className="error">{error}</p>}{result&&<p role="status">{result}</p>}
 {!impact?<p className="muted-cell">Loading consumers…</p>:!impact.consumers.length?<p className="muted-cell">No application bindings.</p>:<div className="operations-table-scroll"><table><thead><tr>{manage&&<th>Select</th>}<th>Application / environment</th><th>Applied</th><th>Status</th></tr></thead><tbody>{impact.consumers.map(c=><tr key={`${c.appId}/${c.alias}`}>{manage&&<td><input type="checkbox" aria-label={`Redeploy ${c.appName} binding ${c.alias}`} disabled={busy||!c.canRedeploy} checked={selected.includes(c.appId)} onChange={e=>{setConfirm(false);setSelected(old=>e.target.checked?[...new Set([...old,c.appId])]:old.filter(id=>id!==c.appId))}}/></td>}<td><strong>{c.appName}</strong><small>{c.environment||"Default environment"} · {c.targetName} · {c.alias}</small><ApplicationDeploymentLink appId={c.appId}/>{onBindings&&<button className="service-bindings-link" onClick={()=>onBindings(c.appId)}>Bindings</button>}</td><td>r{c.appliedRevision||"—"} → r{service.revision}</td><td><span className={c.redeploymentRequired?"operations-warning":"operations-success"}>{c.redeploymentRequired?<WarningCircle size={15}/>:<CheckCircle size={15}/>} {c.redeploymentRequired?"Redeployment required":"Current"}</span>{c.reason&&<small>{c.reason}</small>}</td></tr>)}</tbody></table></div>}
 {manage&&!!impact?.consumers.length&&<div className="operations-actions">{confirm?<><p>Redeploy {selected.length} selected application(s) using their last successful source revision and current service credentials. Running containers may be replaced.</p><button className="primary-button" disabled={busy} onClick={()=>void redeploy()}>{busy?"Accepting deployments…":"Confirm redeploy"}</button><button className="quiet-button" disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></>:<button className="quiet-button" disabled={!selected.length||busy} onClick={()=>setConfirm(true)}><ArrowsClockwise size={15}/>Redeploy selected ({selected.length})</button>}</div>}
 </div>
}
